ALTER TABLE TB_BASE_DADOS ADD FURACAO VARCHAR(10)
ALTER TABLE TB_BASE_DADOS ADD RETRAB_CORTE VARCHAR(10)
ALTER TABLE TB_BASE_DADOS ADD RETRAB_FURACAO VARCHAR(10)
ALTER TABLE TB_BASE_DADOS ALTER DT_TRABALHO TO DT_TRAB_USI
ALTER TABLE TB_BASE_DADOS ADD DT_TRAB_CORTE Date
ALTER TABLE TB_BASE_DADOS ADD DT_TRAB_BORDA Date
ALTER TABLE TB_BASE_DADOS ADD DT_TRAB_FURACAO Date
ALTER TABLE TB_BASE_DADOS ADD DT_TRAB_EMBALAGEM Date
ALTER TABLE TB_BASE_DADOS ALTER RETRABALHO TO RETRAB_USI
ALTER TABLE TB_BASE_DADOS ADD DT_RETRAB_CORTE Date
ALTER TABLE TB_BASE_DADOS ADD DT_RETRAB_BORDA Date
ALTER TABLE TB_BASE_DADOS ADD DT_RETRAB_USI Date
ALTER TABLE TB_BASE_DADOS ADD DT_RETRAB_FURACAO Date